name: firebase_auth_desktop
description: Windows and Linux implementation of firebase_auth
homepage: https://firebase.flutter.dev
repository: https://github.com/invertase/flutterfire_desktop
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  desktop_webview_auth: ^0.0.9
  firebase_auth: ^3.3.7
  firebase_auth_dart: ^1.0.0
  firebase_auth_platform_interface: ^6.1.4
  firebase_core: ^1.12.0
  firebase_core_dart: ^1.0.0
  flutter:
    sdk: flutter
  meta: ^1.3.0
  desktop_webview_auth_tizen:
    path: ../../../../desktop_webview_auth_tizen
  ewk_webview_flutter_tizen:
    path: /home/user/Tizen/projects/ewk_version/packages/ewk_webview_flutter
  webview_flutter: ^3.0.4

dev_dependencies:
  async: ^2.8.1
  firebase_core_platform_interface: ^4.2.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  plugin_platform_interface: ^2.0.2
  flutter_lints: ^2.0.0

flutter:
  plugin:
    implements: firebase_auth
    platforms:
      tizen:
        pluginClass: FirebaseAuthDesktopPlugin
        fileName: firebase_auth_desktop_plugin.h

false_secrets:
  - /example/**

