name: firebase_auth_desktop
description: Windows and Linux implementation of firebase_auth
homepage: https://firebase.flutter.dev
repository: https://github.com/invertase/flutterfire_desktop
version: 1.0.2

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  desktop_webview_auth: ^0.0.8
  firebase_auth: ^3.6.2
  firebase_auth_dart: ^1.0.1
  firebase_auth_platform_interface: ^6.5.2
  firebase_core: ^1.20.0
  firebase_core_dart: ^1.0.1
  flutter:
    sdk: flutter
  meta: ^1.3.0
  webview_flutter: ^3.0.4


dev_dependencies:
  async: ^2.8.1
  firebase_core_platform_interface: ^4.5.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  plugin_platform_interface: ^2.1.2

flutter:
  plugin:
    implements: firebase_auth
    platforms:
      tizen:
        pluginClass: FirebaseAuthDesktopPlugin
        fileName: firebase_auth_desktop_plugin.h

false_secrets:
  - /example/**

