name: firebase_auth_desktop_example
description: Demonstrates how to use the ewk_webview_flutter_tizen plugin.
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  ewk_webview_flutter_tizen:
    path: /home/user/Tizen/projects/ewk_version/packages/ewk_webview_flutter
  flutter:
    sdk: flutter
  path_provider: ^2.0.7
  path_provider_tizen: ^2.0.2
  webview_flutter: ^3.0.4
  desktop_webview_auth: ^0.0.6
  firebase_auth: ^3.3.7
  firebase_auth_desktop: ^0.1.1
  firebase_core: ^1.12.0
  firebase_core_desktop: ^0.1.1
  flutter_lints: ^1.0.4
  flutter_signin_button: ^2.0.0
  google_sign_in: ^5.0.0-nullsafety
  google_sign_in_dartio: ^0.2.0
  yaru: ^0.2.0
  shared_preferences_tizen:

dev_dependencies:
  espresso: ^0.1.0+2
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  pedantic: ^1.10.0
dependency_overrides:
  firebase_auth_desktop:
    path: ../
  firebase_core_desktop:
    path: ../../../firebase_core/firebase_core_desktop

flutter:
  uses-material-design: true
  assets:
    - assets/sample_audio.ogg
    - assets/sample_video.mp4
    - assets/www/index.html
    - assets/www/styles/style.css
